/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chatbot;

import dictionary.Dictionary;
import dictionary.Fragmentation;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author abc
 */
public class ChatGUI extends javax.swing.JFrame {

    /**
     * Creates new form ChatGUI
     */
    public ChatGUI() {
        initComponents();
        init();
    }

    private void init() {
        setVisible(true);
        setResizable(false);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setName("Rozgadany Gienek");
        dictionary.loadDictionary();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        localization = new javax.swing.JTextField();
        localButton = new javax.swing.JButton();
        userText = new javax.swing.JTextField();
        chooser = new javax.swing.JButton();
        saver = new javax.swing.JButton();
        removeDictionary = new javax.swing.JButton();
        ngram = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        botBar1 = new javax.swing.JProgressBar();
        botBar2 = new javax.swing.JProgressBar();
        botBar3 = new javax.swing.JProgressBar();
        userBar1 = new javax.swing.JProgressBar();
        userBar2 = new javax.swing.JProgressBar();
        userBar3 = new javax.swing.JProgressBar();
        conversation = new javax.swing.JScrollPane();
        textArea = new javax.swing.JEditorPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Rozgadany Gienek");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                Save(evt);
            }
        });

        localization.setText("Wprowadź lokalizacje pliku...");
        localization.setToolTipText("Wprowadź lokalizacje pliku...");
        localization.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                localizationMouseClicked(evt);
            }
        });

        localButton.setText("Wczytaj");
        localButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                localButtonActionPerformed(evt);
            }
        });

        userText.setText("Wprowadź tekst...");
        userText.setToolTipText("Wprowadź tekst...");
        userText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userTextMouseClicked(evt);
            }
        });
        userText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                userTextKeyReleased(evt);
            }
        });

        chooser.setText("Wybierz plik");
        chooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooserActionPerformed(evt);
            }
        });

        saver.setText("Zapisz dialog");
        saver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saverActionPerformed(evt);
            }
        });

        removeDictionary.setText("Wyczyść słownik");
        removeDictionary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeDictionaryActionPerformed(evt);
            }
        });

        ngram.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4" }));
        ngram.setToolTipText("Stopień Ngramu");
        ngram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ngramActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel1.setText("Statystyki komputera:");

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setText("Statystyki użytkownika:");

        botBar1.setToolTipText("");
        botBar1.setName("Tak"); // NOI18N
        botBar1.setStringPainted(true);

        botBar2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botBar2.setStringPainted(true);

        botBar3.setStringPainted(true);

        userBar1.setStringPainted(true);

        userBar2.setStringPainted(true);

        userBar3.setStringPainted(true);

        conversation.setViewportView(textArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(localization, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chooser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(localButton))
                    .addComponent(userText)
                    .addComponent(conversation))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(saver)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(removeDictionary)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ngram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botBar2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botBar3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userBar2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userBar3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(11, 11, 11)))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(localization, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(localButton)
                    .addComponent(chooser)
                    .addComponent(saver)
                    .addComponent(removeDictionary)
                    .addComponent(ngram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(conversation)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(botBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botBar3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(userBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(userBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(userBar3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 48, Short.MAX_VALUE))))
        );

        botBar1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userTextMouseClicked
        if (userText.getText().equals("Wprowadź tekst...")) {
            userText.setText("");
        }

    }//GEN-LAST:event_userTextMouseClicked

    private void localizationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_localizationMouseClicked
        if (localization.getText().startsWith("Wprowadź lokalizacje pliku...")) {
            localization.setText("");
        }
    }//GEN-LAST:event_localizationMouseClicked

    private void localButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_localButtonActionPerformed
        File file = new File(localization.getText());
        if (file.isFile()) {
            localization.setText("Wprowadź lokalizacje pliku...");
            fragmentation = new Fragmentation(ngram.getSelectedIndex());
            fragmentation.fragmentationFile(file, dictionary.getPrefixList());
        } else {
            JOptionPane.showMessageDialog(null, "Nie będę się z tego uczył. Daj mi coś innego.", "Gienek", 2);
        }
    }//GEN-LAST:event_localButtonActionPerformed

    private void userTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userTextKeyReleased
        if (evt.getKeyCode() == 10) {
            textArea.setText(textArea.getText() + "Ja: ");
            textArea.setText(textArea.getText() + userText.getText() + "\n");

            fragmentation = new Fragmentation(ngram.getSelectedIndex());
            fragmentation.fragmentationUser(userText.getText(), dictionary.getPrefixList());

            generator = new Generator(userText.getText(), statistic);
            String answer = generator.generate(dictionary.getPrefixList());

            statistic = generator.getStatistic();
            statistic.fillMax();

            userBar1.setValue(statistic.getWordsByUser().get(0).getCounter() * 100 / statistic.getAllUsages());
            userBar1.setString(statistic.getWordsByUser().get(0).getWord() + " - " + ((statistic.getWordsByUser().get(0).getCounter() * 100 / statistic.getAllUsages())) + "%");
            if (statistic.getWordsByUser().size() > 1) {
                userBar2.setValue(statistic.getWordsByUser().get(1).getCounter() * 100 / statistic.getAllUsages());
                userBar2.setString(statistic.getWordsByUser().get(1).getWord() + " - " + ((statistic.getWordsByUser().get(1).getCounter() * 100 / statistic.getAllUsages())) + "%");
            }
            if (statistic.getWordsByUser().size() > 2) {
                userBar3.setValue(statistic.getWordsByUser().get(2).getCounter() * 100 / statistic.getAllUsages());
                userBar3.setString(statistic.getWordsByUser().get(2).getWord() + " - " + ((statistic.getWordsByUser().get(2).getCounter() * 100 / statistic.getAllUsages())) + "%");
            }

            botBar1.setValue(statistic.getWordsByBot().get(0).getCounter() * 100 / statistic.getAllUsages());
            botBar1.setString(statistic.getWordsByBot().get(0).getWord() + " - " + ((statistic.getWordsByBot().get(0).getCounter() * 100 / statistic.getAllUsages())) + "%");
            if (statistic.getWordsByBot().size() > 1) {
                botBar2.setValue(statistic.getWordsByBot().get(1).getCounter() * 100 / statistic.getAllUsages());
                botBar2.setString(statistic.getWordsByBot().get(1).getWord() + " - " + ((statistic.getWordsByBot().get(1).getCounter() * 100 / statistic.getAllUsages())) + "%");
            }
            if (statistic.getWordsByBot().size() > 2) {
                botBar3.setValue(statistic.getWordsByBot().get(2).getCounter() * 100 / statistic.getAllUsages());
                botBar3.setString(statistic.getWordsByBot().get(2).getWord() + " - " + ((statistic.getWordsByBot().get(2).getCounter() * 100 / statistic.getAllUsages())) + "%");
            }

            textArea.setText(textArea.getText() + "Gienek: ");
            textArea.setText(textArea.getText() + answer + "\n");
            userText.setText("");
        }
    }//GEN-LAST:event_userTextKeyReleased

    private void chooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooserActionPerformed
        JFileChooser fChooser = new JFileChooser();
        fChooser.addChoosableFileFilter(new MyFilter());

        if (fChooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            File file = fChooser.getSelectedFile();
            localization.setText(file.getAbsolutePath());
        }
    }//GEN-LAST:event_chooserActionPerformed

    private void removeDictionaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeDictionaryActionPerformed
        int question = JOptionPane.showConfirmDialog(null, " Napewno chcesz pozbawić mnie całej wiedzy?", "Gienek", JOptionPane.YES_NO_OPTION);
        if (question == JOptionPane.YES_OPTION) {
            dictionary.removeDictionary();
            JOptionPane.showMessageDialog(null, "MJKLanakhbsjas", "Gienek", 0);
        } else if (question == JOptionPane.NO_OPTION) {
            JOptionPane.showMessageDialog(null, "Uff, dziękuję przyjacielu!!!", "Gienek", -1);
        }
    }//GEN-LAST:event_removeDictionaryActionPerformed

    private void saverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saverActionPerformed
        JFileChooser fChooser = new JFileChooser();
        fChooser.addChoosableFileFilter(new MyFilter());

        if (fChooser.showSaveDialog(null) == JFileChooser.APPROVE_OPTION) {
            File file = fChooser.getSelectedFile();
            try {
                FileWriter out = new FileWriter(file);
                String text = textArea.getText();
                out.write(text.replaceAll("\n", System.getProperty("line.separator")));
                out.close();
                JOptionPane.showMessageDialog(null, "Zapisałem naszą rozmowę na twoim komputerze.", "Gienek", -1);
            } catch (IOException e) {
                JOptionPane.showMessageDialog(null, "Lepiej żeby tego nikt nie zobaczył.", "Gienek", 2);
                System.out.println("Problem: " + e);
            }
        }
    }//GEN-LAST:event_saverActionPerformed

    private void ngramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ngramActionPerformed
        dictionary.setGrade(ngram.getSelectedIndex());
    }//GEN-LAST:event_ngramActionPerformed

    private void Save(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_Save
        dictionary.saveDictionary();
    }//GEN-LAST:event_Save

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChatGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChatGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChatGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChatGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ChatGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar botBar1;
    private javax.swing.JProgressBar botBar2;
    private javax.swing.JProgressBar botBar3;
    private javax.swing.JButton chooser;
    private javax.swing.JScrollPane conversation;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton localButton;
    private javax.swing.JTextField localization;
    private javax.swing.JComboBox ngram;
    private javax.swing.JButton removeDictionary;
    private javax.swing.JButton saver;
    private javax.swing.JEditorPane textArea;
    private javax.swing.JProgressBar userBar1;
    private javax.swing.JProgressBar userBar2;
    private javax.swing.JProgressBar userBar3;
    private javax.swing.JTextField userText;
    // End of variables declaration//GEN-END:variables

    private final Dictionary dictionary = new Dictionary();
    private Fragmentation fragmentation;
    private Generator generator;
    private Statistic statistic = new Statistic();

    class MyFilter extends javax.swing.filechooser.FileFilter {

        @Override
        public boolean accept(File file) {
            String filename = file.getName();
            return filename.endsWith(".txt");
        }

        @Override
        public String getDescription() {
            return "*.txt";
        }
    }
}
