/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chatbot;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author abc
 */
public class ChatGUI extends javax.swing.JFrame {

    /**
     * Creates new form ChatGUI
     */
    public ChatGUI() {
        initComponents();
        init();
    }

    
    public void init() {
        setVisible(true);
        setResizable(false);

        setLocationRelativeTo(null);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        localization = new javax.swing.JTextField();
        localButton = new javax.swing.JButton();
        userText = new javax.swing.JTextField();
        chooser = new javax.swing.JButton();
        saver = new javax.swing.JButton();
        removeDictionary = new javax.swing.JButton();
        ngram = new javax.swing.JComboBox();
        conversation = new javax.swing.JScrollPane();
        textArea = new javax.swing.JEditorPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        localization.setText("Wprowadź lokalizacje pliku...");
        localization.setToolTipText("Wprowadź lokalizacje pliku...");
        localization.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                localizationMouseClicked(evt);
            }
        });

        localButton.setText("Wczytaj");
        localButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                localButtonActionPerformed(evt);
            }
        });

        userText.setText("Wprowadź tekst...");
        userText.setToolTipText("Wprowadź tekst...");
        userText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userTextMouseClicked(evt);
            }
        });
        userText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                userTextKeyReleased(evt);
            }
        });

        chooser.setText("Wybierz plik");
        chooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooserActionPerformed(evt);
            }
        });

        saver.setText("Zapisz dialog");
        saver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saverActionPerformed(evt);
            }
        });

        removeDictionary.setText("Wyczyść słownik");
        removeDictionary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeDictionaryActionPerformed(evt);
            }
        });

        ngram.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4" }));
        ngram.setToolTipText("Stopień Ngramu");

        conversation.setViewportView(textArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(localization, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chooser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(localButton))
                    .addComponent(conversation)
                    .addComponent(userText))
                .addGap(4, 4, 4)
                .addComponent(saver)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(removeDictionary)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ngram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(localization, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(localButton)
                    .addComponent(chooser)
                    .addComponent(saver)
                    .addComponent(removeDictionary)
                    .addComponent(ngram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(conversation, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userTextMouseClicked
        if (userText.getText().equals("Wprowadź tekst...")) {
            userText.setText("");
        }
    }//GEN-LAST:event_userTextMouseClicked

    private void localizationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_localizationMouseClicked
        if (localization.getText().startsWith("Wprowadź lokalizacje pliku...")) {
            localization.setText("");
        }
    }//GEN-LAST:event_localizationMouseClicked

    private void localButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_localButtonActionPerformed
        File file = new File(localization.getText());
        if (file.isFile()) {
            localization.setText("Wprowadź lokalizacje pliku...");
        } else {
            JOptionPane.showMessageDialog(null, "Nie będę się z tego uczył. Daj mi coś innego.", "Gienek", 2);
        }

    }//GEN-LAST:event_localButtonActionPerformed

    private void userTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userTextKeyReleased
        if (evt.getKeyCode() == 10) {
            if (userText.getText().equals("/exit")) {

            } else {
                textArea.setText(textArea.getText() + userText.getText() + "\n");
                userText.setText("");
            }
        }
    }//GEN-LAST:event_userTextKeyReleased

    private void chooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooserActionPerformed
        JFileChooser fChooser = new JFileChooser();
        fChooser.addChoosableFileFilter(new MyFilter());

        if (fChooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            File file = fChooser.getSelectedFile();
            localization.setText(file.getAbsolutePath());
        }
    }//GEN-LAST:event_chooserActionPerformed

    private void removeDictionaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeDictionaryActionPerformed
        int question = JOptionPane.showConfirmDialog(null, " Napewno chcesz pozbawić mnie całej wiedzy?", "Gienek", JOptionPane.YES_NO_OPTION);
        if (question == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(null, "MJKLanakhbsjas", "Gienek", 0);
        } else if (question == JOptionPane.NO_OPTION) {
            JOptionPane.showMessageDialog(null, "Uff, dziękuję przyjacielu!!!", "Gienek", -1);
        }
    }//GEN-LAST:event_removeDictionaryActionPerformed

    private void saverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saverActionPerformed
        JFileChooser fChooser = new JFileChooser();
        fChooser.addChoosableFileFilter(new MyFilter());

        if (fChooser.showSaveDialog(null) == JFileChooser.APPROVE_OPTION) {
            File file = fChooser.getSelectedFile();
            try {
                FileWriter out = new FileWriter(file);
                String text = textArea.getText();
                out.write(text.replaceAll("\n", System.getProperty("line.separator")));
                out.close();
                JOptionPane.showMessageDialog(null, "Zapisałem naszą rozmowę na twoim komputerze.", "Gienek", -1);
            } catch (IOException e) {
                JOptionPane.showMessageDialog(null, "Lepiej żeby tego nikt nie zobaczył.", "Gienek", 2);
                System.out.println("Problem: " + e);
            }
        }
    }//GEN-LAST:event_saverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChatGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChatGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChatGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChatGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChatGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton chooser;
    private javax.swing.JScrollPane conversation;
    private javax.swing.JButton localButton;
    private javax.swing.JTextField localization;
    private javax.swing.JComboBox ngram;
    private javax.swing.JButton removeDictionary;
    private javax.swing.JButton saver;
    private javax.swing.JEditorPane textArea;
    private javax.swing.JTextField userText;
    // End of variables declaration//GEN-END:variables

    class MyFilter extends javax.swing.filechooser.FileFilter {

        @Override
        public boolean accept(File file) {
            String filename = file.getName();
            return filename.endsWith(".txt");
        }

        @Override
        public String getDescription() {
            return "*.txt";
        }
    }
}
